#!/sbin/sh

export BOOTREC_CACHE_NODE="/dev/block/mtdblock2 b 179 13"
export BOOTREC_CACHE="/dev/block/mtdblock2"
export BOOTREC_EVENT_NODE="/dev/input/event1 c 13 64"
export BOOTREC_EVENT="/dev/input/event1"
export BOOTREC_LED_RED="/sys/class/leds/red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/blue/brightness"
